name: CI - Build HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. (Opsional) Validasi HTML
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: true

      # 3. (Opsional) Archive hasil build
      # - name: Upload HTML artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: site
      #     path: .
